spring:
  mvc:
    #static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true



server:
  port: 11117

filename:
  slope: "C:/Users/王宇/Desktop/apache-tomcat-9.0.65/webapps/ROOT/fireData/LinAnDemSlope_nodata0.tif"
  type: "C:/Users/王宇/Desktop/apache-tomcat-9.0.65/webapps/ROOT/fireData/LinAnForestClass_nodata1.tif"
  direction: ""
  result: "C:/Users/王宇/Desktop/apache-tomcat-9.0.65/webapps/ROOT/fireData/"