spring:
  mvc:
    #static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true



server:
  port: 11117

filename:
  slope: "/home/remote/ffire/apache-tomcat-9.0.65/webapps/ROOT/fireSourceData/LinAnDemSlope_nodata0.tif"
  type: "/home/remote/ffire/apache-tomcat-9.0.65/webapps/ROOT/fireSourceData/LinAnForestClass_nodata1.tif"
  direction: "/home/remote/ffire/apache-tomcat-9.0.65/webapps/ROOT/fireSourceData"
  result: "/home/remote/ffire/apache-tomcat-9.0.65/webapps/ROOT/fireData/"
#  slope: "C:\\code\\java\\javaweb\\t\\FireSpreadModel\\src\\main\\resources\\data\\LinAnDemSlope_nodata0.tif"
#  type: "C:\\code\\java\\javaweb\\t\\FireSpreadModel\\src\\main\\resources\\data\\LinAnForestClass_nodata1.tif"
#  direction: "C:\\code\\java\\javaweb\\t\\FireSpreadModel\\src\\main\\resources\\data\\"
#  result: "C:\\code\\java\\javaweb\\t\\FireSpreadModel\\src\\main\\resources\\data\\"