spring:
  mvc:
    #static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true



server:
  port: 11117

filename:
  slope: "/data/LinAnDemSlope_nodata0.tif"
  type: "/data/LinAnForestClass_nodata1.tif"
  direction: ""
  result: "/static/result.tif"